### Setup

In [97]:
import pandas
import torch
import torch.nn as nn
import numpy as np

### Check Model

In [98]:
'''
Here you can see that the linear transformation uses
the weight matrix and bias matrix.
'''
model = nn.Linear(1, 1)
print(model.state_dict())

OrderedDict([('weight', tensor([[0.9068]])), ('bias', tensor([0.0285]))])


In [114]:
'''
This linear transformation takes a 10 input and returns a 5
output. When checking the values in the transformation, the weight's
shape is (5, 10) but the input is (x, 10) so it might be confusing.
The bias always has the same size as the output dim.
'''
model = nn.Linear(10, 5)
for i, v in model.state_dict().items():
    print(f"index: {i}\t\tshape: {v.shape}")

index: weight		shape: torch.Size([5, 10])
index: bias		shape: torch.Size([5])


In [117]:
'''
As you can see the result is (1, 10) * (10, 5) = (1 * 5)
'''
x = torch.rand(1, 10)
y_hat = model(x)
print(f"Input Shape: {x.shape}")
print(f"Output Shape: {y_hat.shape}")

Input Shape: torch.Size([1, 10])
Output Shape: torch.Size([1, 5])


In [118]:
'''
If the bias option is false the bias is not used
'''
model = nn.Linear(10, 5, bias=False)
for i, v in model.state_dict().items():
    print(f"index: {i}\t\tshape: {v.shape}")

index: weight		shape: torch.Size([5, 10])


In [120]:
'''
If a dtype is specified it will use that dtype.
If there is not a dtype used then it will use the default dtype.
In this case the default dtype is torch.float32
'''
model = nn.Linear(10, 5, dtype=torch.float32)
for i, v in model.state_dict().items():
    print(f"index: {i}\t\tshape: {v.shape}")

index: weight		shape: torch.Size([5, 10])
index: bias		shape: torch.Size([5])


In [121]:
'''
You can use the .weight and .bias to get the matrix for each
'''
model = nn.Linear(10, 5, dtype=torch.float32)
print(f"Model Weight: {model.weight.shape}")
print(f"Model Bias: {model.bias.shape}")

Model Weight: torch.Size([5, 10])
Model Bias: torch.Size([5])


### Run Model

In [103]:
x = torch.rand(40).unsqueeze(1) * 40
print(x.shape)
print(x.squeeze())

torch.Size([40, 1])
tensor([17.0229, 31.7264,  8.4700,  0.2274, 34.4207, 31.8699, 36.1829, 17.4096,
        28.1539,  0.6171, 20.2019, 34.8220, 10.4346,  4.6249, 14.6462, 33.1293,
        24.0936, 10.6691,  5.8224, 13.5482, 28.6915, 27.1263, 24.6706,  3.0260,
         4.1184, 10.8148, 10.7229, 37.2049, 31.4229, 20.5013, 32.7484,  6.4798,
         1.6369, 26.2695, 10.7635,  0.6334, 32.7217,  2.3402, 11.6497, 12.9401])


In [104]:
y = 4 * x + 3
print(y.shape)
print(y.squeeze())

torch.Size([40, 1])
tensor([ 71.0914, 129.9054,  36.8801,   3.9094, 140.6829, 130.4798, 147.7317,
         72.6385, 115.6158,   5.4684,  83.8074, 142.2882,  44.7383,  21.4998,
         61.5850, 135.5173,  99.3744,  45.6765,  26.2897,  57.1929, 117.7659,
        111.5051, 101.6826,  15.1040,  19.4735,  46.2594,  45.8917, 151.8198,
        128.6917,  85.0052, 133.9936,  28.9193,   9.5478, 108.0779,  46.0538,
          5.5336, 133.8868,  12.3607,  49.5988,  54.7603])


In [105]:
model = nn.Linear(1, 1)

In [106]:
y_hat = model(x)
print(y_hat.shape)
print(y_hat.squeeze())

torch.Size([40, 1])
tensor([-1.2825e+01, -2.4348e+01, -6.1223e+00,  3.3737e-01, -2.6459e+01,
        -2.4460e+01, -2.7840e+01, -1.3128e+01, -2.1548e+01,  3.1934e-02,
        -1.5316e+01, -2.6774e+01, -7.6619e+00, -3.1090e+00, -1.0962e+01,
        -2.5447e+01, -1.8366e+01, -7.8457e+00, -4.0474e+00, -1.0102e+01,
        -2.1970e+01, -2.0743e+01, -1.8818e+01, -1.8559e+00, -2.7120e+00,
        -7.9599e+00, -7.8879e+00, -2.8641e+01, -2.4110e+01, -1.5551e+01,
        -2.5149e+01, -4.5626e+00, -7.6730e-01, -2.0071e+01, -7.9196e+00,
         1.9148e-02, -2.5128e+01, -1.3184e+00, -8.6141e+00, -9.6254e+00],
       grad_fn=<SqueezeBackward0>)


In [107]:
if y_hat.shape == y.shape:
    print("The result has the same shape")
else:
    print("The result has a different shape")

The result has the same shape


In [108]:
loss_fn = nn.MSELoss()

In [109]:
optimizer = torch.optim.Adam(model.parameters(), 0.05)

In [110]:
for epoch in range(100):
    y_hat = model(x)
    
    loss = loss_fn(y_hat, y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"epoch: {epoch + 1}:\t\tloss: {loss}")

epoch: 1:		loss: 10996.8740234375
epoch: 2:		loss: 10764.009765625
epoch: 3:		loss: 10533.7060546875
epoch: 4:		loss: 10306.0048828125
epoch: 5:		loss: 10080.947265625
epoch: 6:		loss: 9858.5732421875
epoch: 7:		loss: 9638.9208984375
epoch: 8:		loss: 9422.0263671875
epoch: 9:		loss: 9207.923828125
epoch: 10:		loss: 8996.646484375
epoch: 11:		loss: 8788.2216796875
epoch: 12:		loss: 8582.6806640625
epoch: 13:		loss: 8380.046875
epoch: 14:		loss: 8180.3447265625
epoch: 15:		loss: 7983.5947265625
epoch: 16:		loss: 7789.81494140625
epoch: 17:		loss: 7599.0224609375
epoch: 18:		loss: 7411.2294921875
epoch: 19:		loss: 7226.4501953125
epoch: 20:		loss: 7044.6904296875
epoch: 21:		loss: 6865.95703125
epoch: 22:		loss: 6690.2568359375
epoch: 23:		loss: 6517.58984375
epoch: 24:		loss: 6347.955078125
epoch: 25:		loss: 6181.35107421875
epoch: 26:		loss: 6017.77294921875
epoch: 27:		loss: 5857.212890625
epoch: 28:		loss: 5699.66259765625
epoch: 29:		loss: 5545.11181640625
epoch: 30:		loss: 5393.5458